version: '3'
services:
  nginx:
    image: fabiocicerchia/nginx-lua:latest
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 9999:9999

  geoip:
    image: ghcr.io/observabilitystack/geoip-api
    ports:
      - 8081:8080